version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - automerge
  ignore:
  - dependency-name: symfony/polyfill-php80
    versions:
    - 1.22.1
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.76
  - dependency-name: phpstan/phpstan-symfony
    versions:
    - 0.12.18
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.3
  - dependency-name: symfony/cache
    versions:
    - 5.2.3
