version: '3.7'
services:
    cli:
        image: ghcr.io/shyim/php-cli:8.0
        env_file: .env.docker
        tty: true
        volumes:
            - ./:/var/www/html/
    web:
        image: friendsofshopware/packages
        build:
          context: .
        env_file: .env.docker
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html/
    redis:
        image: redis:5-alpine
    mysql:
        image: mysql:8
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_USER: packages
            MYSQL_PASSWORD: packages
            MYSQL_DATABASE: packages
        command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    search:
        image: getmeili/meilisearch:latest
        command: ['./meilisearch']
        ports:
            - 7700:7700
    adminer:
        image: adminer
        ports:
            - 8080:8080
