version: '3.7'
services:
    web:
        image: shyim/shopware-platform-nginx:php74
        env_file: .env.docker
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html/
    redis:
        image: redis:5-alpine
    mysql:
        image: mysql:8
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_USER: packages
            MYSQL_PASSWORD: packages
            MYSQL_DATABASE: packages
        command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    elasticsearch:
        image: elasticsearch:7.5.1
        command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]
    adminer:
        image: adminer
        ports:
            - 8080:8080
