apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: plugin-sync
  namespace: packages-friendsofshopware-com
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync-store-plugins
              image: friendsofshopware/packages
              envFrom:
                - configMapRef:
                    name: app-config
              args:
                - /bin/sh
                - -c
                - bin/console internal:package:import $SBP_USER $SBP_PASSSWORD
          restartPolicy: Never
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-sync
  namespace: packages-friendsofshopware-com
spec:
  schedule: "50 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync-elastic-index
              image: friendsofshopware/packages
              envFrom:
                - configMapRef:
                    name: app-config
              args:
                - php
                - bin/console
                - search:package:index
          restartPolicy: Never
