sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        excluded_exceptions:
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
            - App\Exception\InvalidTokenHttpException
            - App\Exception\AccessDeniedToDownloadPluginHttpException
            - App\Exception\InvalidShopGivenHttpException
