name: Deploy Dev
on:
    push:
        branches: live

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: symfonycorp/security-checker-action@v2

            - name: Build image and push
              run: |
                  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "shyim" --password-stdin
                  docker build -t friendsofshopware/packages:stage  --build-arg GIT_TAG=$GITHUB_SHA .
                  docker push friendsofshopware/packages:stage