name: Deploy Live
on:
    release:
        types: [ published ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

            - name: Setup SSH Keys and known_hosts
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan pikachu.shyim.de >> ~/.ssh/known_hosts
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                  ssh-add - <<< "${{ secrets.DEPLOY_SSH_KEY }}"

            - name: Deploy
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  git remote add deploy deploy@pikachu.shyim.de:packages
                  git push -u deploy ${{ steps.get_version.outputs.VERSION }}
                  
            - name: Create Sentry release
              uses: getsentry/action-release@v1
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
              with:
                environment: production
                version: "${{ steps.get_version.outputs.VERSION }}"
